matrix:
  include:
   - os: osx
     osx_image: xcode10.2
     env: CC=gcc-8 CXX=g++-8
     language: java

cache:
  directories:
  - $HOME/.m2
  - $HOME/Library/Caches/Homebrew

install:
  - brew install gcc@8

deploy:
  provider: s3
  access_key_id: AKIAJ562PU6WBV5MJJHQ
  secret_access_key:
    secure: ypVAzWr6MiAccYWQAgTrRDS7dzlAu9tkcXhK61goLvCUCdilqKnyWI3i2D82LRfabhT7P2gTt2xct3fo1cSozL8TvIsTct/pNnqFZaMo2XwaOPStxUwbJd7UFBCGPHaqrPm9yyVl2a/5zpRVEsrpVd0nB9ikKtzZntXP2+a698wKV5i3QBoK4QGFh8P5+Y3/gCRbhCmN9A3+QpOOoXupDwNRsfU7GzIk/xvVOTfN1GJxtvC58F0Q9wRko/EUGiaQ2kN1qnu8ND6smA1+of/rsaTng9K62MibUYIvguDTOfnV4VTIC6p4SB1NkmNmvLrzZwrWqs6K1OvCg34Aq765Nskvu70onfXxfywWo4CDraVBml7y1bevVbQ7Cf7P+rkjSomrwB0LmpxIpkQ0kCnr5/hRCF2yHq8NLIcHyxszPurFmjteLvHldCpu1UV1U+y9actFVmBKCWEtrTuxRBBvWb5OWc2nuJS/bIXOkc3L55jK9K3qlT1FcAnBvelmb7XwmGDJG7KOj8B25UDbA2+P8focAqakg0qrPONmyZEJmpuYHlkx93RflpfDX/Qg+mqhLzsndR5B5NZFFMOH4XY7E8MrYATXy0IVnKpJ8F1OUISbhjkqTiV4kZcKZAPCKs1tgckqnKOFXuIc4E7WZZhKiD5Zf1mCmHVkWVbMDxpZlro=
  skip_cleanup: true
  bucket: webfolderio
  upload-dir: duktape4j-macos
  region: eu-west-1
  acl: public_read
  on:
    repo: webfolderio/duktape4j

script:
  - cd native && ./build-macos.sh && cd ..
  - mvn -q -DskipTests clean package
  - mvn -q surefire-report:report
  - rm -rf native/duktape/
  - rm -rf native/duktape-android/
  - rm -rf target/
