matrix:
  include:
   - os: osx
     osx_image: xcode9.4
     env: CC=gcc-8 CXX=g++-8
     language: java

cache:
  directories:
  - $HOME/.m2

before_install:
  - brew cask uninstall oclint

install:
  - softwareupdate --list
  - softwareupdate --install "Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.4"
  - brew install gcc@8

script:
  - cd native && ./build-macos.sh
  - mvn -q -DskipTests clean package
  - mvn -q surefire-report:report
