os:
  - osx

language: java

cache:
  directories:
  - $HOME/.m2

before_install:
  - brew link --overwrite gcc

script:
  - cd native && ./build-macos.sh
  - mvn -q -DskipTests clean package
  - mvn -q surefire-report:report
