matrix:
  include:
   - os: osx
     osx_image: xcode9.4
     language: java
     env: CC=gcc-8 CXX=g++-8

cache:
  directories:
  - $HOME/.m2

before_install:
  - brew unlink gcc
  - brew unlink g++
  - brew install gcc

script:
  - cd native && ./build-macos.sh
  - mvn -q -DskipTests clean package
  - mvn -q surefire-report:report
