matrix:
  include:
   - os: osx
     language: java

cache:
  directories:
  - $HOME/.m2

before_install:
  - brew cask uninstall oclint
  - brew install gcc@8

script:
  - cd native && ./build-macos.sh
  - mvn -q -DskipTests clean package
  - mvn -q surefire-report:report
