version: 1.0.'{build}'

branches:
  only:
    - master

skip_tags: true

skip_non_tags: true

skip_branch_with_pr: true

platform: x64

configuration: Release

environment:
  matrix:
    - MSYS2_ARCH: x86_64
      MSYS2_BITS: 64

install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://www-us.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
      $env:Path +=";C:\maven\apache-maven-3.5.4\bin;%JAVA_HOME%\bin"
build_script:
  - cd native && build.bat
  - mvn test
