version: 1.0.'{build}'
image: Visual Studio 2017

branches:
  only:
    - master

skip_tags: true
skip_non_tags: true
skip_branch_with_pr: true
platform: x64
configuration: Release

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

before_build:
  - set PATH=C:\msys64\mingw64;C:\msys64\mingw64\bin;C:\msys64\usr\bin\;%PATH%

build_script:
  - cd native && build.bat
  - mvn -DskipTests -q clean package

test_script:
  - mvn -q test

  artifacts:
  - path: src\main\resources\META-INF\duktape.dll
    name: Duktape DLL