version: '{build}'

skip_tags: true

# enviroment settings
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - cmd: echo %JAVA_HOME%
  - cmd: echo %M2_HOME%

build_script:
  - mvn clean package -DskipTests

test_script:
  - mvn -q test

cache:
  - C:\maven\
  - C:\Users\appveyor\.m2