version: 1.0.'{build}'
image: Visual Studio 2017

branches:
  only:
    - master

skip_tags: true
skip_non_tags: true
skip_branch_with_pr: true
platform: x64
configuration: Release

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

before_build:
  - set PATH=C:\msys64\mingw64;C:\msys64\mingw64\bin;C:\msys64\usr\bin\;%PATH%

build_script:
  - cd native && build-msvc.bat
  - mvn -DskipTests -q clean package

test_script:
  - mvn -q surefire-report:report

after_test:
  - ps: |
        $wc = New-Object 'System.Net.WebClient'
        Get-ChildItem . -Name -Recurse 'TEST-*.xml'  |
        Foreach-Object {
            $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $_))
        }

artifacts:
  - path: src\main\resources\META-INF\duktape.dll
    name: Duktape DLL