version: 1.0.'{build}'

 branches:
  only:
    - master

 skip_tags: true
 skip_non_tags: true
 skip_branch_with_pr: true
 platform: x64
 configuration: Release

 environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

build_script:
  - cd native && build-mingw.bat
  - mvn -q test